---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-gateway-githedgehog-com-v1alpha1-peering
  failurePolicy: Fail
  name: mpeering-v1alpha1.kb.io
  rules:
  - apiGroups:
    - gateway.githedgehog.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - peerings
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gateway-githedgehog-com-v1alpha1-peering
  failurePolicy: Fail
  name: vpeering-v1alpha1.kb.io
  rules:
  - apiGroups:
    - gateway.githedgehog.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - peerings
  sideEffects: None
