# This rule is not used by the project gateway itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to gwint.githedgehog.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/managed-by: kustomize
  name: gwint-gatewayagent-viewer-role
rules:
- apiGroups:
  - gwint.githedgehog.com
  resources:
  - gatewayagents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gwint.githedgehog.com
  resources:
  - gatewayagents/status
  verbs:
  - get
