# This rule is not used by the project gateway itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the gwint.githedgehog.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/managed-by: kustomize
  name: gwint-gatewayagent-editor-role
rules:
- apiGroups:
  - gwint.githedgehog.com
  resources:
  - gatewayagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gwint.githedgehog.com
  resources:
  - gatewayagents/status
  verbs:
  - get
