# This rule is not used by the project gateway itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over gateway.githedgehog.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/managed-by: kustomize
  name: peeringinterface-admin-role
rules:
- apiGroups:
  - gateway.githedgehog.com
  resources:
  - peeringinterfaces
  verbs:
  - '*'
- apiGroups:
  - gateway.githedgehog.com
  resources:
  - peeringinterfaces/status
  verbs:
  - get
